name: "Python: Linting - Type Checking - Formatting - Unit Testing"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  app-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install -r requirements/tests-requirements.txt
        pip install -r requirements/dev-requirements.txt
    - name: Linting
      run: |
        python -m pylint src/
        python -m pylint tests/
    - name: Type checking
      run: |
        python -m mypy src/
    - name: Unit testing
      run: |
        python -m pytest --cov=src --cov-config=tests/.coveragerc tests
